-- Soft delete + auditoria basica para a lista compartilhada

alter table if exists public.items
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by_nome text,
  add column if not exists delete_reason text;

create index if not exists idx_items_periodo_deleted_at
  on public.items (periodo_id, deleted_at);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  action text not null,
  collaborator_name text,
  period_id text,
  item_id text,
  details jsonb not null default '{}'::jsonb,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_log_created_at
  on public.audit_log (created_at desc);

create index if not exists idx_audit_log_action
  on public.audit_log (action);

-- Se RLS estiver ativo nessas tabelas, ajuste as policies conforme sua regra.
